version: '3.8'
services:
  test_server:
    build: ./test_server
    container_name: test_server
    volumes:
      - "./test_server:/app"
    ports:
      - 8080:8080
    networks:
      - docproj-network
    depends_on:
      - log_server

  recorddb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - volrecdb:/var/lib/postgresql/data
    networks:
      - docproj-network

  log_server:
    build: ./log_server
    container_name: log_server_container
    ports:
      - 8001:8001
      - 8002:8002
    networks:
      - docproj-network
    depends_on:
      - logserverdb

  logserverdb:
    build: ./log_db
    restart: always
    hostname: logdb
    container_name: log_database_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - vollogdb:/var/lib/postgresql/data
      - ./log_db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - docproj-network

volumes:
  volrecdb:
    driver: local
  vollogdb:
    driver: local

networks:
  docproj-network:
    driver: bridge
