version: '3'
services:
  nginx:
   container_name: webserver-nginx
   image: nginx:1.13
   ports:
     - 80:80
   volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
    - web-server-app
   networks:
    - docproj-network #web-server_network

  web-server-app:
    container_name: web-server-container
    build: ../docker-compose-proj
    working_dir: /web-server
    volumes:
      - dbvol:/web-server
    expose:
      - 8080
    networks:
      - docproj-network #web-server_network
    depends_on:
      - recorddb
  recorddb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - volrecdb:/var/lib/postgresql/data
#      - ./db/record-init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - docproj-network

volumes:
  dbvol:
    driver: local
  volrecdb:
    driver: local

networks:
  docproj-network:
    driver: bridge
    
#networks:
#  web-server_network:
#    driver: bridge
  