version: '3.8'
services:
  recorddb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - volrecdb:/var/lib/postgresql/data
    networks:
      - docproj-network

  logserverdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - vollogdb:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - docproj-network

volumes:
  volrecdb:
    driver: local
  vollogdb:
    driver: local

networks:
  docproj-network:
    driver: bridge
