version: '3.8'
services:
  recorddb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - dbvol:/var/lib/postgresql/data

volumes:
  dbvol:
    driver: local